#!/usr/bin/env bash

## Description: Truncate tables (within the DDEV-hosted database) that need not be exported to database dumps.

(
cat << END
UPDATE db.be_users
SET
    userMods=NULL,
    uc='',
    lastlogin=0;

TRUNCATE TABLE db.be_sessions;
TRUNCATE TABLE db.fe_sessions;

UPDATE db.sys_registry
SET entry_value=NULL
WHERE entry_namespace='core' AND entry_key LIKE 'formProtectionSessionToken:%';

TRUNCATE TABLE db.cache_treelist;
TRUNCATE TABLE db.cf_cache_hash;
TRUNCATE TABLE db.cf_cache_hash_tags;
TRUNCATE TABLE db.cf_cache_imagesizes;
TRUNCATE TABLE db.cf_cache_imagesizes_tags;
TRUNCATE TABLE db.cf_cache_pages;
TRUNCATE TABLE db.cf_cache_pages_tags;
TRUNCATE TABLE db.cf_cache_pagesection;
TRUNCATE TABLE db.cf_cache_pagesection_tags;
TRUNCATE TABLE db.cf_cache_rootline;
TRUNCATE TABLE db.cf_cache_rootline_tags;

TRUNCATE TABLE db.cf_extbase_datamapfactory_datamap;
TRUNCATE TABLE db.cf_extbase_datamapfactory_datamap_tags;
TRUNCATE TABLE db.cf_extbase_object;
TRUNCATE TABLE db.cf_extbase_object_tags;
TRUNCATE TABLE db.cf_extbase_reflection;
TRUNCATE TABLE db.cf_extbase_reflection_tags;
TRUNCATE TABLE db.cf_extbase_typo3dbbackend_queries;
TRUNCATE TABLE db.cf_extbase_typo3dbbackend_queries_tags;

TRUNCATE TABLE db.sys_file_processedfile;

TRUNCATE TABLE db.sys_lockedrecords;

TRUNCATE TABLE db.sys_history;
TRUNCATE TABLE db.sys_log;

TRUNCATE TABLE db.sys_refindex;
END
) | mysql
