#!/usr/bin/env bash

## Description: Setup repository for development after cloning.

set -x

# NOTE: We don't need to call "ddev start" here, because this is being run as a DDEV command

# Clone extension
git clone --branch fix-compatibility git@github.com:Deutsche-Digitale-Bibliothek/ddb-frontend-viewer.git extensions/ddb-frontend-viewer/

# Install dependencies
ddev composer install

# Import database dump
ddev db-import

# Create some default TYPO3 folders
ddev typo3cms install:fixfolderstructure
